module-name: application-connector-manager
kind: kyma
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/application-connector-manager:1.1.11
  - europe-docker.pkg.dev/kyma-project/prod/central-application-gateway:v20250411-2e63148e
  - europe-docker.pkg.dev/kyma-project/prod/central-application-connectivity-validator:v20250411-2e63148e
  - europe-docker.pkg.dev/kyma-project/prod/compass-runtime-agent:v20250411-1bd93c30
mend:
  language: golang-mod
  exclude:
    - "**/*_test.go"
checkmarx-one:
    preset: go-default
    exclude:
        - '**/*_test.go'
