module-name: application-connector-manager
kind: kyma
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/application-connector-manager:1.1.10
  - europe-docker.pkg.dev/kyma-project/prod/central-application-gateway:v20250403-2fe746fb
  - europe-docker.pkg.dev/kyma-project/prod/central-application-connectivity-validator:v20250403-2fe746fb
  - europe-docker.pkg.dev/kyma-project/prod/compass-runtime-agent:v20250404-e64a8df5
mend:
  language: golang-mod
  exclude:
    - "**/*_test.go"
checkmarx-one:
    preset: go-default
    exclude:
        - '**/*_test.go'
