name: compass-runtime-agent-unit-test
on:
  push:
    branches: [ "main" ]
  pull_request:
permissions:
  contents: read
jobs:
  cra-unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up go environment
      uses: actions/setup-go@v5
      with:
        go-version-file: components/compass-runtime-agent/go.mod
        cache-dependency-path: components/compass-runtime-agent/go.sum
    - name: Run unit tests
      working-directory: ./components/
      run: make test-cra
