name: central-connectivity-validator-unit-test
on:
  push:
    branches: [ "main" ]
  pull_request:
permissions:
  contents: read
jobs:
  validator-unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up go environment
      uses: actions/setup-go@v5
      with:
        go-version-file: components/central-application-connectivity-validator/go.mod
        cache-dependency-path: components/central-application-connectivity-validator/go.sum
    - name: Run unit tests
      working-directory: ./components/
      run: make test-validator
